/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
    /*Tier 1 Questions */
    //Load `7` into r0 and `12` into r1. Add them, store the result in r2.
    /*__asm volatile("mov r0, #7 \n\t"
                   "mov r1, #12 \n\t"
                   "add r2, r0, r1 \n\t");*/

    //Load `20` into r0. Subtract `8` from it using `SUBS`. What does `SUBS` (vs `SUB`) set as a side effect, and why does that matter?
    /*__asm volatile("mov r0,#20 \n\t"
                   "subs r0, r0, #8 \n\t");*/

    //Multiply two small numbers using `MULS`. Predict the result before running it.
     
    /*__asm volatile("mov r0, #3 \n\t"
                   "mov r1, #4 \n\t"
                   "muls r2, r0, r1 \n\t");*/

    /*Tier 2 Questions */
    
    // Declare `volatile int x = 42;` in C. Write inline assembly that reads `x` into r0, adds `1`, and writes it back to `x`. Confirm in C that `x` is now 43.
    /*volatile int x = 42;
    __asm volatile("add %0, %0, #1 \n\t" : "=r"(x) : "0"(x));
    return x;*/

    //
   /* uint32_t arr[5] = {1, 2, 3, 4, 5};
    uint32_t result;
    __asm volatile("ldr %0,[%1,#8] \n\t"
                  : "=r"(result) 
                : "r"(arr));*/
    
   /* uint32_t arr[5] = {1, 2, 3, 4, 5};
    __asm volatile("str %1,[%0,#12] \n\t"
                    :
                    : "r"(arr),"r"(99)
                    :"memory");
    printf("%lu \n",arr[3]);*/


    /* Tier 3 Questions */

    //Write a loop that counts from 0 to 9 in a register, using `CMP` and `BNE`
    /*__asm volatile("mov r0 ,#0 \n\t"
                   "LOOP: \n\t"
                   "cmp r0, #9 \n\t"
                   "add r0, r0, #1 \n\t"
                   "bne LOOP \n\t"); */

    // Sum the values of a 5-element array into one register, using a loop
    /*uint32_t arr[5] = {1,2,3,4,5};
    uint32_t result;
       __asm volatile(
        "mov %0, #0 \n\t"
        "mov r1, #0 \n\t"
        "1: \n\t"
        "ldr r2, [%1, r1, lsl #2] \n\t"
        "add %0, %0, r2 \n\t"
        "add r1, r1, #1 \n\t"
        "cmp r1, #5 \n\t"
        "bne 1b \n\t"
        : "=&r"(result)          
        : "r"(arr)
        : "r1", "r2", "cc", "memory"
    );*/
    //Write a loop that finds the **largest** value in an array. You'll need a second comparison inside the loop body, not just the loop-exit check.

   /*uint32_t arr[5] = {1,2,3,4,5};
    uint32_t max_value;
    __asm volatile("mov %0,#0\n\t"
                    "mov r1, #0\n\t"
                    "mov r2, %1\n\t"
                    "1: \n\t"
                    "ldr r3, [%1, r1, lsl #2] \n\t"
                    "cmp r3, %0 \n\t"
                    "ble 2f \n\t"
                    "mov %0, r3 \n\t"
                    
                    "2: \n\t"
                    "add r1, r1, #1 \n\t"
                    "cmp r1, #5 \n\t"
                    "bne 1b \n\t"

                    : "=&r"(max_value)
                    : "r"(arr)
                    : "r1","r2","r3","cc" ,"memory"); */

    // Write a loop that finds the **smallest** value in an array. You'll need a second comparison inside the loop body, not just the loop-exit check.
    /*uint32_t arr[5] = {1,2,3,4,5};
    uint32_t min_value;

    __asm volatile("mov %0,#0xFFFFFFFF \n\t"
                    "mov r1,#0\n\t"
                    "1: \n\t"
                    "ldr r2, [%1, r1,lsl #2] \n\t");
                    "cmp r2, %0 \n\t"
                    "bge 2f \n\t"
                    "mov %0, r2 \n\t"
                    "2: \n\t"
                    "add r1, r1, #1 \n\t"
                    "cmp r1, #5 \n\t"
                    "bne 1b \n\t"
                    : "=&r"(min_value)
                    : "r"(arr)
                    : "r1","r2","cc" ,"memory");*/

    
        
for(;;);
    }