/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    //Question 1. Load `7` into r0 and `12` into r1. Add them, store the result in r2.
    /*__asm volatile("mov r0, #7 \n\t"
                   "mov r1, #12 \n\t"
                   "add r2, r0, r1 \n\t");*/

    

	for(;;);
}
