/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




 /*Calculate the bit band alias address for given bit band memory address and bit position

7th bit position of the memory location 0x2000_0200 using its alias address*/
#include <stdint.h>
#define ALIAS_BASE 0x22000000U
#define BITBAND_BASE 0x20000000U
int main(void)
{
    uint8_t* ptr = (uint8_t*)0x20000200; /* Pointer to the memory location */
    *ptr = 0xff;

    //normal method. 
    //clearing 7th bit position
    *ptr &= ~(1<<7);

    //reset to 0xff
    *ptr = 0xff;

    //bit band method
    
    uint8_t* alias_addr = (uint8_t*)(ALIAS_BASE + (0x20000200 - BITBAND_BASE) * 32 + 7 * 4); /* Calculate the alias address */

    *alias_addr = 0;

    //clearing 7th bit of address 0x20000200
    /* Loop forever */
	for(;;);
}
