/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "my_tools.h"

void uart_gpio_init(void){
    GPIOA_MODER &= ~(3UL<<4);
    GPIOA_MODER |= (2UL<<4);

    GPIOA_AFRL &= ~(0xFUL<<8);
    GPIOA_AFRL |= (7UL<<8);
}

void uart2_init(void){
    USART2_CR1 &= ~(1UL<<13);
    USART2_BRR = 0x0683;
    USART2_CR1 |= (1UL<<3);
    USART2_CR1 |= (1UL<<13);
}

void uart2_write(int ch) {
    while (!(USART2_SR & (1UL << 7)));
    USART2_DR = (ch & 0xFF);
}

void uart2_print(const char *str) {
    while (*str) {
        while (!(USART2_SR & (1U << 7))); 
        USART2_DR = (*str & 0xFF);
        str++;
    }
}

int main(void)
{
    RCC_AHB1ENR |= RCC_AHB1ENR_GPIOAEN;

    RCC_APB1ENR |= RCC_APB1ENR_USART2EN;

    uart_gpio_init();
    uart2_init();

   

    /* Loop forever */
	for(;;){
    uart2_print("Hello from bare-metal STM32!\r\n");
    for(int i = 0; i < 1000000; i++);
    }
}
