/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    // __asm volatile("LDR R1,=#0x20001000\n\t"
    //                "LDR R2,=#0x20001004\n\t"
    //                "LDR R0,[R1]\n\t"
    //                "LDR R1,[R2]\n\t"
    //                 "ADD R0,R0,R1\n\t"
    //                "STR R0,[R2]\n\t");
    int val =50;

    __asm volatile("MOV R0, %0"::"r"(val));

    //copy the value of CONTROL register to control_reg variable
    int control_reg;
    __asm volatile("MRS %0,CONTROL":"=r"(control_reg)::);

    //copy the value of c variables var 1  to var 2
    int var1 = 10;
    int var2;
    __asm volatile("MOV %0, %1":"=r"(var2):"r"(var1));

    //copy the contents of a pointer to another variable
    int * ptr1=(int*)0x20000008;
    int ptr2;
    __asm volatile("LDR %0,[%1]":"=r"(ptr2):"r"(ptr1));
    
    /* Loop forever */
	for(;;);
}
