/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
    __asm volatile("LDR R1,=#0x20001000\n\t"
                   "LDR R2,=#0x20001004\n\t"
                   "LDR R0,[R1]\n\t"
                   "LDR R1,[R2]\n\t"
                    "ADD R0,R0,R1\n\t"
                   "STR R0,[R2]\n\t");
    /* Loop forever */
	for(;;);
}
